version: '2.6'

# PORT for web application, nginx, redis and database will change based on Port documentation on Dev and Prod server

services:
  geneticsweb:
    container_name: genetics-ark-web
    image: genetics-ark-web:2.0.3
    platform: linux/amd64
    build:
      dockerfile: web.Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && gunicorn ga_core.wsgi:application --bind :8003 --timeout 300 --workers 2 --threads 4"
    restart: always
    env_file:
      - /Users/jason/Github/Genetics_Ark/.env
    volumes:
      - igv_volume:/home/ga/DNAnexus_to_igv/jsons # read updated BAM json file
      - static_volume:/home/ga/staticfiles # staticfiles
      - /Users/jason/Github/Genetics_Ark/logs # write logging
      - /Users/jason/Github/Genetics_Ark/reference:/reference_files # refs for primer designer
    expose:
      - 8003 # expose port within the container ONLY
    depends_on:
      - geneticsdb
  geneticscron:
    container_name: genetics-ark-cron
    image: genetics-ark-cron:add_komodo_monitoring
    platform: linux/amd64
    restart: always
    build: ./cron
    command: bash -c "printenv > /etc/environment && cron -f"
    env_file:
      - /Users/jason/Github/Genetics_Ark/.env
    volumes:
      - primer_volume:/home/tmp # to clear generated pdfs
      - igv_volume:/home/jsons # to update the sample json
      - /Users/jason/Github/Genetics_Ark/logs:/home/log # cron job logging
  geneticsnginx:
    container_name: genetics-ark-nginx
    image: nginx:1.23
    platform: linux/amd64
    restart: always
    volumes:
      - /Users/jason/Github/Genetics_Ark/reference:/reference_files # serve igv references through nginx
      - primer_volume:/tmp # zip generated primer designer PDFs
      - static_volume:/staticfiles # serve staticfiles
      - /Users/jason/Github/Genetics_Ark/logs:/home/ga/log # logging for nginx
      - /Users/jason/Github/Genetics_Ark/nginx:/etc/nginx/conf.d # nginx config
    expose:
      - 8002
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/genetics_ark
    depends_on:
      - geneticsweb
  redis:
    # container_name: genetics-ark-redis
    # platform: linux/amd64
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
  geneticsdjangoq:
    image: genetics-ark-djangoq:2.0.3
    platform: linux/amd64
    container_name: genetics-ark-djangoq
    build:
      dockerfile: primer.Dockerfile
    command: python manage.py qcluster
    restart: always
    env_file:
      - /Users/jason/Github/Genetics_Ark/.env
    volumes:
      - primer_volume:/home/primer_designer/output # zip generated primer designer PDFs
      - /Users/jason/Github/Genetics_Ark/reference:/reference_files # refs for primer designer
    depends_on:
      - redis
  geneticsdb:
    container_name: genetics-ark-db
    # platform: linux/amd64
    image: mysql:8
    ports:
      - 3307:3308
    env_file:
      - /Users/jason/Github/Genetics_Ark/.env
    volumes:
      - genetics_db:/var/lib/mysql

volumes:
  static_volume:
  primer_volume:
  igv_volume:
  genetics_db:


networks:
  default:
    name: nginx-default
    external: true
