version: '3.3'
services:
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn ga_core.wsgi:application --bind :8000 --workers 3"
    env_file:
      - /home/lingj-loc/config.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # to call host docker
      - /usr/bin/docker:/usr/bin/docker # to call host docker
      - /home/lingj-loc/tmp:/home/ga/tmp # zip generated primer designer PDFs
      - /home/lingj-loc/jsons:/home/ga/DNAnexus_to_igv/jsons # read updated BAM json file
      - /var/log:/home/ga/logs # write logging
      - static_volume:/home/ga/staticfiles # staticfiles
    expose:
      - 8000
  cron:
    build: .
    command: bash -c "printenv > /etc/environment && cron -f"
    env_file:
      - /home/lingj-loc/config.txt
    volumes:
      - /home/lingj-loc/tmp:/home/ga/tmp # clear generated primer designer PDFs
      - /home/lingj-loc/jsons:/home/ga/DNAnexus_to_igv/jsons # update BAM jsons
  nginx:
    build: ./nginx
    volumes:
      - /appdata/refs:/home/ga/reference_files # serve igv references
      - /home/lingj-loc/tmp:/home/ga/tmp # zip generated primer designer PDFs
      - static_volume:/home/ga/staticfiles # serve staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web
volumes:
  static_volume: