version: '2.6'
services:
  web:
    image: ga_web:2.0
    build:
      dockerfile: web.Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && gunicorn ga_core.wsgi:application --bind :8000 --timeout 300 --workers 2 --threads 4"
    env_file:
      - /home/jason/github/Genetics_Ark/.env
    volumes:
      # - primer_volume:/home/primer_designer/output # zip generated primer designer PDFs
      - igv_volume:/home/ga/DNAnexus_to_igv/jsons # read updated BAM json file
      - static_volume:/home/ga/staticfiles # staticfiles
      - /home/jason/github/Genetics_Ark/logs:/home/ga/logs # write logging
      - /home/jason/github/reference:/reference_files # refs for primer designer
    expose:
      - 8000 # expose port within the container ONLY
    depends_on:
      - db
  cron:
    image: ga_cron:2.0
    build: ./cron
    command: bash -c "printenv > /etc/environment && cron -f"
    env_file:
      - /home/jason/github/Genetics_Ark/.env
    volumes:
      - primer_volume:/home/tmp # to clear generated pdfs
      - igv_volume:/home/jsons # to update the sample json
      - /home/jason/github/Genetics_Ark/logs:/home/log # cron job logging
  nginx:
    image: ga_ngx:2.0
    build: ./nginx
    volumes:
      - /home/jason/github/reference:/reference_files # serve igv references through nginx
      - primer_volume:/tmp # zip generated primer designer PDFs
      - static_volume:/staticfiles # serve staticfiles
      - /home/jason/github/Genetics_Ark/logs:/home/ga/log # logging for nginx
    # ports:
    #   - "80:80" # define port
    expose:
      - 8001
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/genetics_ark
    depends_on:
      - web
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
  djangoq:
    image: ga_djangoq:2.0
    build:
      dockerfile: primer.Dockerfile
    command: python manage.py qcluster
    env_file:
      - /home/jason/github/Genetics_Ark/.env
    volumes:
      - primer_volume:/home/primer_designer/output # zip generated primer designer PDFs
      - /home/jason/github/reference:/reference_files # refs for primer designer
    depends_on:
      - redis
  db:
    container_name: genetics_db
    image: mysql:8
    environment:
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    env_file:
      - /home/jason/github/Genetics_Ark/.env
    volumes:
      - genetics_db:/var/lib/mysql

volumes:
  static_volume:
  primer_volume:
  igv_volume:
  genetics_db:

networks:
  default:
    name: nginx_default
    external: true