version: '3.3'

# PORT for web application, nginx, redis and database will change based on Port documentation on Dev and Prod server
services:
  geneticsweb:
    container_name: genetics-ark-web
    image: genetics-ark-web:2.0.3
    command: bash -c "python manage.py collectstatic --noinput && gunicorn ga_core.wsgi:application --bind :8000 --timeout 300 --workers 2 --threads 4"
    platform: linux/amd64
    build:
      dockerfile: web.Dockerfile
    restart: always
    env_file:
      - ${GA_CONFIG_PATH}
    volumes:
      - igv_volume:/home/ga/DNAnexus_to_igv/jsons # read updated BAM json file
      - static_volume:/home/ga/staticfiles # staticfiles
      - ${LOG_PATH}:/home/ga/logs # write logging
      - ${REF_PATH}:/reference_files # refs for primer designer
    expose:
      - 8001 # expose port within the container ONLY
    depends_on:
      - geneticsdb
  geneticscron:
    container_name: genetics-ark-cron
    image: genetics-ark-cron:add_komodo_monitoring
    platform: linux/amd64
    restart: always
    build: ./cron
    command: bash -c "printenv > /etc/environment && cron -f"
    volumes:
      - primer_volume:/home/tmp # to clear generated pdfs
      - igv_volume:/home/jsons # to update the sample json
      - ${LOG_PATH}:/home/log # cron job logging
  geneticsnginx:
    container_name: genetics-ark-nginx
    image: nginx:1.23
    platform: linux/amd64
    restart: always
    volumes:
      - ${REF_PATH}:/reference_files # serve igv references through nginx
      - primer_volume:/tmp # zip generated primer designer PDFs
      - static_volume:/staticfiles # serve staticfiles
      - ${LOG_PATH}:/home/ga/log # logging for nginx
      - ${GA_PATH}/nginx:/etc/nginx/conf.d # nginx config
    expose:
      - 8002
    depends_on:
      - geneticsweb
  redis:
    container_name: genetics-ark-redis
    image: redis:7-alpine
    platform: linux/amd64
    restart: always
    ports:
      - 6379:6379
  geneticsdjangoq:
    image: genetics-ark-djangoq:2.0.3
    platform: linux/amd64
    container_name: genetics-ark-djangoq
    build:
      dockerfile: primer.Dockerfile
    command: python manage.py qcluster
    restart: always
    env_file:
      - ${GA_CONFIG_PATH}
    volumes:
      - primer_volume:/home/primer_designer/output # zip generated primer designer PDFs
      - ${REF_PATH}:/reference_files # refs for primer designer
    depends_on:
      - redis
  geneticsdb:
    # platform: linux/amd64
    container_name: genetics-ark-db
    image: mysql:8
    expose:
      - 3306
    env_file:
      - ${GA_CONFIG_PATH}
    volumes:
      - genetics_db:/var/lib/mysql

volumes:
  static_volume:
  primer_volume:
  igv_volume:
  genetics_db:

networks:
  default:
    name: nginx-default
    external: true
