# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Runfolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('samples', models.IntegerField(blank=True, null=True)),
                ('total_reads', models.IntegerField(blank=True, null=True)),
                ('mapped_reads', models.IntegerField(blank=True, null=True)),
                ('duplicate_reads', models.IntegerField(blank=True, null=True)),
                ('mean_isize', models.FloatField(blank=True, null=True)),
                ('bases_on_target', models.FloatField(blank=True, null=True)),
                ('bases_100x_coverage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'runfolder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('aaf', models.FloatField(blank=True, db_column='AAF', null=True)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('gq', models.FloatField(blank=True, db_column='GQ', null=True)),
                ('allele_count', models.IntegerField()),
            ],
            options={
                'db_table': 'sample_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reads', models.IntegerField(blank=True, null=True)),
                ('mapped_reads', models.IntegerField(blank=True, null=True)),
                ('duplicate_reads', models.IntegerField(blank=True, null=True)),
                ('mean_isize', models.FloatField(blank=True, null=True)),
                ('mean_het_ratio', models.FloatField(blank=True, null=True)),
                ('mean_homo_ratio', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('capture', models.CharField(blank=True, max_length=80, null=True)),
                ('bases_on_target', models.FloatField(blank=True, null=True)),
                ('mean_target_coverage', models.FloatField(blank=True, null=True)),
                ('coverage_0x', models.FloatField(blank=True, db_column='0x_coverage', null=True)),
                ('coverage_2x', models.FloatField(blank=True, db_column='2x_coverage', null=True)),
                ('coverage_10x', models.FloatField(blank=True, db_column='10x_coverage', null=True)),
                ('coverage_20x', models.FloatField(blank=True, db_column='20x_coverage', null=True)),
                ('coverage_30x', models.FloatField(blank=True, db_column='30x_coverage', null=True)),
                ('coverage_40x', models.FloatField(blank=True, db_column='40x_coverage', null=True)),
                ('coverage_50x', models.FloatField(blank=True, db_column='50x_coverage', null=True)),
                ('coverage_100x', models.FloatField(blank=True, db_column='100x_coverage', null=True)),
            ],
            options={
                'db_table': 'stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=8)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('annotation_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'variant',
                'managed': False,
            },
        ),
    ]
