# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='decon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deconcnv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='decongene',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='decongenecnv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deconsample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
