# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-28 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0002_auto_20190528_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='analysisvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gene',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genepanel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelregion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='runfolder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='samplepanel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transcriptregion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={},
        ),
    ]
