# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-28 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0004_auto_20190528_0843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cnv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='decon',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deconcnv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='decongene',
            table=None,
        ),
        migrations.AlterModelTable(
            name='decongenecnv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deconsample',
            table=None,
        ),
    ]
