# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-06 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0008_auto_20190606_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deconcnv',
            name='BF',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deconcnv',
            name='CNV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.CNV'),
        ),
        migrations.AlterField(
            model_name='deconcnv',
            name='correlation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deconcnv',
            name='decon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Decon'),
        ),
    ]
