# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0010_auto_20190612_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNV_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cnv_target',
            },
        ),
        migrations.CreateModel(
            name='DeconAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.FloatField()),
                ('start_b', models.PositiveIntegerField()),
                ('end_b', models.PositiveIntegerField()),
                ('nb_exons', models.PositiveIntegerField()),
                ('BF', models.FloatField()),
                ('reads_expected', models.PositiveIntegerField()),
                ('reads_observed', models.PositiveIntegerField()),
                ('reads_ratio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deconcnv',
            name='CNV',
        ),
        migrations.RemoveField(
            model_name='deconcnv',
            name='decon',
        ),
        migrations.RemoveField(
            model_name='deconcnv',
            name='sample',
        ),
        migrations.AddField(
            model_name='decon',
            name='runfolder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Runfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deconexon',
            name='ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='decon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Decon'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='deconexon',
            index=models.Index(fields=['name'], name='genetics_ar_name_967628_idx'),
        ),
        migrations.AddIndex(
            model_name='deconexoncnv',
            index=models.Index(fields=['deconexon'], name='genetics_ar_deconex_c892f1_idx'),
        ),
        migrations.AddIndex(
            model_name='deconexoncnv',
            index=models.Index(fields=['CNV'], name='genetics_ar_CNV_id_470f43_idx'),
        ),
        migrations.AlterModelTable(
            name='cnv',
            table='cnv',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='decon',
            table='decon',
        ),
        migrations.DeleteModel(
            name='DeconCNV',
        ),
        migrations.AddField(
            model_name='deconanalysis',
            name='CNV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.CNV'),
        ),
        migrations.AddField(
            model_name='deconanalysis',
            name='decon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Decon'),
        ),
        migrations.AddField(
            model_name='cnv_target',
            name='decon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Decon'),
        ),
        migrations.AddField(
            model_name='cnv_target',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Reference'),
        ),
        migrations.AddIndex(
            model_name='deconanalysis',
            index=models.Index(fields=['decon'], name='genetics_ar_decon_i_9491d5_idx'),
        ),
        migrations.AddIndex(
            model_name='deconanalysis',
            index=models.Index(fields=['CNV'], name='genetics_ar_CNV_id_7cc088_idx'),
        ),
    ]
