# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetics_ark', '0011_auto_20190613_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='decon',
        ),
        migrations.AddField(
            model_name='deconanalysis',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='genetics_ark.Sample'),
            preserve_default=False,
        ),
    ]
