# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=6)),
                ('chrom_no', models.CharField(max_length=2)),
                ('start_coordinate_37', models.IntegerField(null=True, verbose_name='GRCh37 Start')),
                ('end_coordinate_37', models.IntegerField(null=True, verbose_name='GRCh37 End')),
                ('start_coordinate_38', models.IntegerField(null=True, verbose_name='GRCh38 Start')),
                ('end_coordinate_38', models.IntegerField(null=True, verbose_name='GRCh38 End')),
            ],
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_37', models.CharField(max_length=50, null=True, verbose_name='GRCh37 Coverage')),
                ('coverage_38', models.CharField(max_length=50, null=True, verbose_name='GRCh38 Coverage')),
            ],
        ),
        migrations.CreateModel(
            name='PCRProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gene', models.CharField(max_length=15)),
                ('sequence', models.CharField(max_length=100)),
                ('gc_percent', models.FloatField(verbose_name='GC %')),
                ('tm', models.FloatField()),
                ('comments', models.TextField(max_length=500, null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=20, null=True, verbose_name='Storage location')),
                ('snp_status', models.CharField(default=0, max_length=1, null=True, verbose_name='SNP')),
                ('snp_info', models.TextField(max_length=500, null=True)),
                ('snp_date', models.DateField(blank=True, null=True)),
                ('buffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Buffer')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Coordinates')),
                ('pairs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_db.Pairs')),
                ('pcr_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.PCRProgram', verbose_name='PCR Program')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='scientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Scientist'),
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Status'),
        ),
    ]
