# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buffer D', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordiantes', models.CharField(max_length=200)),
                ('chrom_no', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PCRProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_program', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=50, unique=True)),
                ('sequence', models.CharField(max_length=100)),
                ('gc_percent', models.FloatField()),
                ('tm', models.FloatField()),
                ('length', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('arrival_date', models.DateField(auto_now_add=True)),
                ('buffer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Buffer')),
                ('pcr_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.PCRProgram')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grch37', models.CharField(max_length=10)),
                ('grch38', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='scientist_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Scientist'),
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Status'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='primer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.PrimerDetails'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='ref_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.Reference'),
        ),
    ]
