# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffer',
            name='buffer_ID',
            field=models.CharField(default='Buffer D', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_ID',
            field=models.CharField(choices=[('o', 'On order'), ('i', 'In bank'), ('a', 'Archived')], max_length=200, primary_key=True, serialize=False),
        ),
    ]
