# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-02 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerdetails',
            name='last_date_used',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
    ]
