# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0002_auto_20190717_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerdetails',
            old_name='buffer_ID',
            new_name='buffer',
        ),
        migrations.RenameField(
            model_name='primerdetails',
            old_name='pcr_ID',
            new_name='pcr',
        ),
        migrations.RenameField(
            model_name='primerdetails',
            old_name='scientist_ID',
            new_name='scientist',
        ),
        migrations.RenameField(
            model_name='primerdetails',
            old_name='status_ID',
            new_name='status',
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='coordiantes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='primer_db.Coordinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerdetails',
            name='reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='primer_db.Reference'),
            preserve_default=False,
        ),
    ]
