# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-02 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0002_primerdetails_last_date_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerdetails',
            name='last_date_used',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 15, 38, 38, 64953, tzinfo=utc)),
        ),
    ]
