# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0003_auto_20190717_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='coordiantes',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='end_coordiante',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinates',
            name='start_coordiante',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
