# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0004_auto_20190717_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerdetails',
            old_name='coordiantes',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='primer_ID',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='ref_ID',
        ),
        migrations.RemoveField(
            model_name='primerdetails',
            name='reference',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='reference',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
