# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0005_auto_20190717_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerdetails',
            name='arrival_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='primerdetails',
            name='gc_percent',
            field=models.IntegerField(),
        ),
    ]
