# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0006_auto_20190717_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerdetails',
            name='arrival_date',
            field=models.DateField(auto_now=True),
        ),
    ]
