# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0008_auto_20190717_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primerdetails',
            old_name='pcr',
            new_name='pcr_program',
        ),
        migrations.AlterField(
            model_name='primerdetails',
            name='arrival_date',
            field=models.DateField(),
        ),
    ]
