# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-17 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0009_auto_20190717_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='end_coordiante',
            new_name='end_coordinate',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='start_coordiante',
            new_name='start_coordinate',
        ),
    ]
