# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0010_auto_20190717_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='end_coordinate',
            new_name='end_coordinate_37',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='start_coordinate',
            new_name='start_coordinate_37',
        ),
        migrations.AlterField(
            model_name='primerdetails',
            name='gc_percent',
            field=models.IntegerField(verbose_name='GC %'),
        ),
        migrations.AlterField(
            model_name='primerdetails',
            name='pcr_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_db.PCRProgram', verbose_name='PCR Program'),
        ),
    ]
