# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0011_auto_20190724_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='end_coordinate_37',
            field=models.CharField(max_length=20, verbose_name='GRCh37 End'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='start_coordinate_37',
            field=models.CharField(max_length=20, verbose_name='GRCh37 Start'),
        ),
        migrations.AlterField(
            model_name='primerdetails',
            name='gc_percent',
            field=models.FloatField(verbose_name='GC %'),
        ),
    ]
