# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0012_auto_20190726_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='end_coordinate_38',
            field=models.IntegerField(blank=True, null=True, verbose_name='GRCh38 End'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='start_coordinate_38',
            field=models.IntegerField(blank=True, null=True, verbose_name='GRCh38 Start'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='end_coordinate_37',
            field=models.IntegerField(blank=True, null=True, verbose_name='GRCh37 End'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='start_coordinate_37',
            field=models.IntegerField(blank=True, null=True, verbose_name='GRCh37 Start'),
        ),
    ]
