# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db', '0014_auto_20190802_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerdetails',
            name='location',
            field=models.CharField(default=None, max_length=20, verbose_name='Storage location'),
            preserve_default=False,
        ),
    ]
